### ISSUE TITLE
Localisation for country specificities (incl. currency) 

### ISSUE THREAD

**Issue by Skrattoune** [Skrattoune/OpenRepairPlatform#1]
Salut,

je propose d'introduire dans settings/base.py les variables globales suivantes afin de faciliter l'intégration dans la branche commune de spécificités pays telles que:
1/ monnaie
2/ gestion zip codes
3/ ... à déterminer aussi en fonction du degré d'intégration qu'on voudra obtenir, tout en permettant une intégration totale

```
COUNTRY = 'FR'  #'CH', 'US' 

CURRENCIES = {
	'FR' : ['EUR', '€'],
	'CH' : ['CHF', 'CHF'],
	'US' : ['USD', '$'],
}
CURRENCY_DISPLAY = CURRENCIES[COUNTRY][1]
CURRENCY_CODE = CURRENCIES[COUNTRY][0]

```
Ca serait ok pour vous?

L'idée pour moi ce serait d'avoir toujours un comportement par défaut qui est le comportement en France,
et si nécessaire un comportement spécifique le cas échéant suivant le pays:
```
if settings.COUNTRY == 'CH':
    pass # adaptation des variables pour la suisse
```
ou 
```
if settings.COUNTRY == 'CH':
    pass #comportement pour CH
else:
   pass #comportement par défaut (pour FR)
```

OK aussi sur le principe?

si vous êtes ok sur le principe, je peux faire l'implémentation, y compris sur le display de la monnaie (qui est le truc qu'on doit absolument faire avant de pouvoir mettre la plateforme en service chez nous)

**Comment by Skrattoune** [comment]
Bon, j'ai trouvé et implémenté en local une meilleure solution (plus robuste) pour ce qui est des currencies basé sur un filtre lié à locale (cf https://www.djangosnippets.org/snippets/552/).

Par contre avant de commiter, j'aurais besoin de vérifier en local que le filtre est bien importé sur toutes les pages où il est appelé, mais pour ça j'ai besoin de faire tourner le serveur en local.

du coup, si quelqu'un peut m'aider à faire lancer le serveur, ça serait cool (cf #160 )

Merci d'avance

**Comment by Skrattoune** [comment]
copy of https://github.com/AtelierSoude/OpenRepairPlatform/issues/158

**Comment by Skrattoune** [comment]
https://dev-openrepairplateform.repaircafes.ch/repaircafe-lausanne/
ValueError at /repaircafe-lausanne/
Currency formatting is not possible using the 'C' locale.
cf: https://stackoverflow.com/questions/2952790/problems-trying-to-format-currency-with-python-django#:~:text=Currency%20formatting%20is%20not%20possible%20using%20the%20'C'%20locale.,-where%20as%20it&text=And%20it%20turned%20out%20if,who%20encounter%20the%20same%20problem.

**Comment by Skrattoune** [comment]
issue fixed

**Comment by nfavrod** [comment]
Hello.
J'ai remarqué quelques petits nouveaux bugs liés à Currency.

![Screenshot_20220312-121205.png](https://user-images.githubusercontent.com/1118004/158015763-39b281a1-c7c8-4adc-a7d2-27dcf09afd3a.png)

https://dev-openrepairplateform.repaircafes.ch/event/book/eyJ1c2VyX2lkIjoxLCJldmVudF9pZCI6MX0:1nSzex:fhk_1j4bL_Uvl4Rm0twuOX3uFEhsiJT1RXD0wZEYC-0/?redirect=None

J'ouvre un nouvau ticket ou on utilise celui ci ?

**Comment by nfavrod** [comment]
Ici aussi

https://dev-openrepairplateform.repaircafes.ch/repaircafe-lausanne/accounting/

![Screenshot_20220312-125358.png](https://user-images.githubusercontent.com/1118004/158016986-34d432f4-f910-4b85-8601-ca7a2432ae41.png)

**Comment by nfavrod** [comment]
https://dev-openrepairplateform.repaircafes.ch/repaircafe-lausanne/controls/

![Screenshot_20220312-125616.png](https://user-images.githubusercontent.com/1118004/158017041-09cfd0ca-479b-407a-9ee1-d3fa5a11b8da.png)

**Comment by Skrattoune** [comment]
ok, ça doit être bon.
J'ai vérifié partout que l'import au templatetags était effectué.
C'était exactement ce que j'avais anticipé: il faut aussi faire l'import dans les templates, y compris dans le fichier txt

seul endroit où l'import n'est pas fait mais ou il est fait référence au filtre currency: 
- openrepairplatform\static\js\vue\apps\event-form\components\EventStepThree.vue
- openrepairplatform\static\js\vue\apps\event-form\components\EventStepFour.vue

à voir à l'usage s'il faut faire un import ou pas... et comment

**Comment by nfavrod** [comment]
@Skrattoune : on y est presque, mais pas tout à fait encore...
https://dev-openrepairplateform.repaircafes.ch/repaircafe-lausanne/controls/ -> toujours le même soucis, currency filter

et ici ça me semble être un autre bug, 
https://dev-openrepairplateform.repaircafes.ch/repaircafe-lausanne/accounting/ -> TypeError at /repaircafe-lausanne/accounting/
for linkify=True, 'Nicolas Favrod-Coune-RepairCafé Lausanne' must have a method get_absolute_url

**Comment by Skrattoune** [comment]
bon, effectivement il y a un fichier qui était passé entre les mailles du filet.
Réparé.

pour le 2e, c'est le genre d'erreur où la stack donne absolument aucune info.
Je vais faire des essais pour déterminer l'origine

**Comment by Skrattoune** [comment]
```
{% comment %} <h4 class="text-center w-100">Total = {{total_fees|currency}} </h4> {% endcomment %}
<h4 class="text-center w-100">Total = {{total_fees}} </h4>
```
gives the same error => error probably already present in reparons.org
Du coup absolument pas lié à currency, mais je traite quand meme sur cette issue:

all other items used in `django_tables2` seem to have a `get_absolute_url` => probably forces to create a link for all table headers

=> added a `get_absolute_url` - but wasn't able to determine exactly which page to link
this one chosen for the moment:
`
reverse("organization_fees", kwargs={"orga_slug": self.organization.slug})
`

**Comment by Skrattoune** [comment]
ok. Ca marche, et j'ai repéré le bon link à mettre: vers le user 
fermeture de l'issue ... j'espère pour de bon cette fois

**Comment by Skrattoune** [comment]
@nfavrod j'aimerais ouvrir la page `https://dev-openrepairplateform.repaircafes.ch/user/11/`
sur `#v-pills-membership` plutot que sur `#v-pills-membership`

mais le lien `https://dev-openrepairplateform.repaircafes.ch/user/11/#v-pills-membership` ne me donne pas le résultat escompté.

est-ce que tu saurais comment faire pour pouvoir ouvrir ce tab spécifiquement à partir de l'url ?

une fois que c'est fait, on peut fermer l'issue à nouveau

**Comment by nfavrod** [comment]
Non pas trouvé l'url...

**Comment by Skrattoune** [comment]
tu arriverais à jetter un coup d'oeil à ces liens et à nous implémenter une solution?
t'es plus fort que moi dans ces trucs javascript / html:
https://getbootstrap.com/docs/5.0/components/navs-tabs/#javascript-behavior
https://stackoverflow.com/a/49806929/12505071

**Comment by nfavrod** [comment]
> tu arriverais à jetter un coup d'oeil à ces liens et à nous implémenter une solution?
> t'es plus fort que moi dans ces trucs javascript / html:
> https://getbootstrap.com/docs/5.0/components/navs-tabs/#javascript-behavior
> https://stackoverflow.com/a/49806929/12505071
> 

Yes je regarde comment faire.

**Comment by Skrattoune** [comment]
- [ ] Nico: implémenter ouverture directe sur tab `https://dev-openrepairplateform.repaircafes.ch/user/11/#v-pills-membership`  à partir de l'URL

**Comment by Skrattoune** [comment]
concernant le point que j'ai soulevé dans #5 concernant les mentions à `ateliersoude` / `atelier-soude` / `reparons`: 
- [ ] Nico: at some point, change name of the database `ateliersoude` in `clean_database.sh` (there should be another place where it is defined as the / a working database
je pense que j'ai trouvé (dans `openrepairplatform\settings\base.py`):
```
DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": os.getenv("POSTGRES_DBNAME", "ateliersoude"),
    }
}
```
mais je propose d'attendre d'avoir quelque chose qui marche bien sur `dev-openrepairplateform.repaircafes.ch` avant de vérifier qu'il n'y a pas un autre endroit à l'extérieur de l'appli à changer

- [ ] at some point, clarify use of `.vscode\settings.json` and make necessary changes

*** moved to issue  #19 ***

le reste du code à été passé en revue !

**Comment by Skrattoune** [comment]
Les points restants ont été bougés sur #28 et #19

Je ferme l'issue
