### ISSUE TITLE
On ne peut pas ajouter de lien dans les descriptions (format texte) 

### ISSUE THREAD

**Issue by nfavrod** [Skrattoune/OpenRepairPlatform#15]
<img width="625" alt="Capture d’écran 2022-03-11 à 00 59 48" src="https://user-images.githubusercontent.com/1118004/157775635-c2502ef9-e724-465c-bf66-66185fda02bb.png">

**Comment by Skrattoune** [comment]
sais pas pourquoi ça marche pas:
utilisation de [tinymce](https://django-tinymce.readthedocs.io/en/latest/usage.html#creating-external-link-and-image-views) dans   [fields.py](https://github.com/Skrattoune/OpenRepairPlatform/tree/dev_branch/openrepairplatform/fields.py) mais `a` et `href `sont allowed 
```
description = CleanHTMLField(
        verbose_name=_(
            "Description supplémentaire de l'événément "
            "(remplace la définition par défaut de l'activité)"
        ),
        blank=True,
    )

```
par contre, dans l'aide en ligne, il est signalé 'si le module est actif':
![image](https://user-images.githubusercontent.com/56255427/158035434-5cb93077-4004-42eb-a717-9ca47fd6f60e.png)
peut etre il y a un lien ... car on peut créer le lien ... mais ce n'est pas accepté ensuite à la validation du champ:
```

class CleanHTMLField(HTMLField):
    def clean(self, value, model_instance):
        value = super().clean(value, model_instance).replace("\r", "")
        value = value.replace("<br />", "<br>")
        ALLOWED_TAGS = [
            'a', 'abbr', 'acronym', 'address', 'area', 'aria-label', 'b', 'big',
            'blockquote', 'br', 'caption', 'center', 'cite', 'code', 'col',
            'colgroup', 'dd', 'del', 'dfn', 'dir', 'div', 'dl', 'dt', 'em',
            'font', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'hr', 'i', 'img',
            'ins', 'kbd', 'label', 'legend', 'li', 'map', 'menu', 'ol',
            'p', 'pre', 'q', 's', 'samp', 'small', 'span', 'strike',
            'strong', 'sub', 'sup', 'u', 'ul', 'var', 'section', 'article', 'div'
        ]
        ALLOWED_ATTRS = [
            "style",
            "href",
            "class",
        ]
        ALLOWED_STYLES = [
            "text-decoration",
            "text-decoration-line",
            "color",
        ]
        cleaned_value = bleach.clean(
            value,
            tags=ALLOWED_TAGS,
            attributes=ALLOWED_ATTRS,
            styles=ALLOWED_STYLES,
            strip=True,
        )
        if cleaned_value != value:
            raise ValidationError("Le format n'est pas autorisé.")
        return value
```

using https://pypi.org/project/bleach/

il faut faire essai sur console python pour tester sur la base de la doc de bleach:
https://bleach.readthedocs.io/en/latest/clean.html#allowed-tags-tags

**Comment by Skrattoune** [comment]
Je cherche.
en théorie ça devrait marcher juste de rajouter `target` dans les attr

**Comment by Skrattoune** [comment]
bon, ça ne suffit pas apparemment. vais être obligé de voir dans la console ce qui se passe.

Par contre, tu peux créer des liens qui s'ouvrent dans la même fenêtre en attendant

Je trouve ça bete la facon dont ca marche actuellement (dire uniquement que ce n'est pas compatible)
Je préfèrerais que ça convertisse en virant simplement les trucs pas compatibles
=> mais plus compliqué à implémenter (formulaires...)

**Comment by Skrattoune** [comment]
Bon, en fait îl rajoute dans les liens aussi un attribut `rel` :
```
<a href="https://polesud.ch/" target="_blank" rel="noopener">P&ocirc;le Sud</a>
```
suffit pas ...
après vérification dans la page elle-même, il a réussi à rajoutter encore un truc `data-mce-href`:
`<a href="https://polesud.ch/" target="_blank" rel="noopener" data-mce-href="https://polesud.ch/">Pôle Sud</a>`

**Comment by Skrattoune** [comment]
alors le `data-mce-href` est uniquement interne ... donc pas de consequences

par contre, l'origine de tout ce problème, c'est que `tiny-mce` et `bleach `mettent les attributs `rel `et `target `dans un ordre différent !!!!!!
pour `bleach`:
```
'<p><a href="https://polesud.ch/" rel="noopener" target="_blank">P&ocirc;le '
 'Sud</a></p>\n'
```

pour `tiny-mce`:
```
'<p><a href="https://polesud.ch/" target="_blank" rel="noopener">P&ocirc;le '
 'Sud</a></p>\n'
```

et la façon dont le code est écrit, il ne doit y avoir aucune différence entre le code nettoyé et le code original

Seule solution: ne pas faire le raise exception et passer le code nettoyé
