### ISSUE TITLE
Changer la petite flèche du menu User 

### ISSUE THREAD

**Issue by nfavrod** [Skrattoune/OpenRepairPlatform#17]
<img width="313" alt="Capture d’écran 2022-03-11 à 01 04 58" src="https://user-images.githubusercontent.com/1118004/157776094-9212a500-57a2-4b00-b808-049cd096411b.png">

Et sur Githu
<img width="212" alt="Capture d’écran 2022-03-11 à 01 05 48" src="https://user-images.githubusercontent.com/1118004/157776121-5cc5ee09-607b-4796-8a24-681b1b663065.png">
b

**Comment by Skrattoune** [comment]
pas compris l'issue?

**Comment by nfavrod** [comment]
Quand tu es connecté, tu ne vois pas la petite fleche pour ouvrir le menu déroulant

[](https://user-images.githubusercontent.com/1118004/157776094-9212a500-57a2-4b00-b808-049cd096411b.png)


, alors que sur github elle est comme ça 👍
![](https://user-images.githubusercontent.com/1118004/157776121-5cc5ee09-607b-4796-8a24-681b1b663065.png)

**Comment by nfavrod** [comment]
Changer la couleur de la petite flèche de gris à blanc :-)

**Comment by Skrattoune** [comment]
dans `openrepairplatform\templates\menu.html`
```
<div class="navbar-brand arrow-login">
      <a class="nav-link me-2 dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class=""></i>
      </a>
```

~~l'icone est déclarée en `text-secondary` tel que defini par `bootstrap `au lieu d'utiliser les couleurs du thème~~

mais normalement, selon `openrepairplatform\static\scss\openrepairplatform.scss`, les couleurs bootstrap devraient être adaptée au thème:
```
@import "../node_modules/bootstrap/scss/bootstrap.scss";

/* others resets */
$theme-colors: (
  "primary": $primary,
  "secondary": $secondary,
  "success": $success,
  "danger": $danger,
) !default;

```

je ne sais pas pourquoi ça ne marche pas.
Il faut voir si les primary-secondary marche mais pas les `text-primary`
=> quand est fait la génération des `alert-primary`, `text-primary`, `bg-primary` ...

**Comment by Skrattoune** [comment]
Après vérification, les couleurs bootstrap sont bien updatées d'après le thème du site. donc ok

Par contre il manquait une information pour définir la couleur de la flèche
