### ISSUE TITLE
L'URL du lien - copier le lien ical , manque le https

### ISSUE THREAD

**Issue by nfavrod** [Skrattoune/OpenRepairPlatform#23]
L?URL copiée ici fait une erreur : 

![Capture d’écran 2022-03-13 à 00 57 33](https://user-images.githubusercontent.com/1118004/158039180-e419a6ea-105e-4f25-9851-7b477fda4480.png)
/

Il faut donc modifier l'URL, sinon on ne peut pas s'abonner.
de : dev-openrepairplateform.repaircafes.ch/event/ical-events/1/
à : https://dev-openrepairplateform.repaircafes.ch/event/ical-events/1

**Comment by Skrattoune** [comment]
@nfavrod  : Si pour la prochaine fois tu arrive à me donner systèmatiquement l'url à partir de laquelle on génère l'erreur, c'est beaucoup plus pratique pour moi

je répare

**Comment by nfavrod** [comment]
https://dev-openrepairplateform.repaircafes.ch/repaircafe-lausanne/events/

**Comment by Skrattoune** [comment]
merci, j'avais trouvé ;-) c'est plutôt pour les prochaines fois.

Bon, j'aurais pas fait comme ça perso, mais bon, j'ai corrigé dans l'esprit de l'implémentation initiale ... après quelques recherches
