### ISSUE TITLE
Erreur lors de l'édition d'un événement en mode admin

### ISSUE THREAD

**Issue by nfavrod** [Skrattoune/OpenRepairPlatform#49]
https://www.repaircafes.ch/admin/event/event/28/change

<img width="804" alt="Capture d’écran 2022-08-19 à 10 05 58" src="https://user-images.githubusercontent.com/1118004/185573964-6d76d242-4708-4dc4-aa0e-f4f317c3821f.png">
/

``

**Comment by nfavrod** [comment]
<div id="summary">
  <h1>RecursionError
       at /admin/event/event/28/change/</h1>
  <pre class="exception_value">maximum recursion depth exceeded while getting the repr of an object</pre>
  

Request Method: | GET
-- | --
https://www.repaircafes.ch/admin/event/event/28/change/
3.2.2
RecursionError
maximum recursion depth exceeded while getting the repr of an object
/srv/app/./openrepairplatform/event/models.py, line 41, in __str__
/usr/local/bin/uwsgi
3.9.12
['.',  '',  '/usr/local/lib/python39.zip',  '/usr/local/lib/python3.9',  '/usr/local/lib/python3.9/lib-dynload',  '/usr/local/lib/python3.9/site-packages',  '/usr/local/lib/python3.9/site-packages/odf',  '/usr/local/lib/python3.9/site-packages/odf',  '/usr/local/lib/python3.9/site-packages/odf',  '/usr/local/lib/python3.9/site-packages/odf',  '/usr/local/lib/python3.9/site-packages/odf',  '/usr/local/lib/python3.9/site-packages/odf',  '/usr/local/lib/python3.9/site-packages/odf']
Fri, 19 Aug 2022 10:05:52 +0200

</div>

**Comment by nfavrod** [comment]
Error during template rendering

In template /usr/local/lib/python3.9/site-packages/django/contrib/admin/templates/admin/includes/fieldset.html, error at line 19
maximum recursion depth exceeded while getting the repr of an object

**Comment by nfavrod** [comment]
Salut @Skrattoune ! On arrive à régler ce soucis car je n'arrive plus à publier ou modifier les événements  ! Thanks

**Comment by Skrattoune** [comment]
Ben...  je viens depuis août tous les Jeudi pour régler le problème originel dont j'ai trouvé l'origine et la solution pendant mes vacances.
On ne peut rien corriger avant d'avoir réglé ce problème.

Tu n'as jamais le temps où tu n'es pas là.
On peut faire ça le Jeudi de la semaine suivante.

**Comment by nfavrod** [comment]
Hello - okay le soucis était dans le fichier models.py - il y avait une récussion Error en lien avec les conditions de participation et les prix. J'ai pu fixer le problème :-)
