### ISSUE TITLE
L'affichage de la zone "à propos" doit être améliorée : BTN, contenu tronqué malgré la taille du calque, etc.

### ISSUE THREAD

**Issue by nfavrod** [Skrattoune/OpenRepairPlatform#8]
<img width="920" alt="Capture d’écran 2022-03-11 à 00 42 35" src="https://user-images.githubusercontent.com/1118004/157774055-8c1b3bc5-d6ce-4d1e-ad9a-bc96fa50098f.png">
<img width="909" alt="Capture d’écran 2022-03-11 à 00 44 25" src="https://user-images.githubusercontent.com/1118004/157774228-bff73273-cf96-4980-ba41-8cae8de434b2.png">

**Comment by Skrattoune** [comment]
je suis passé à 60 char au lieu de 30
